name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Start virtual display (Xvfb)
        run: Xvfb :1 -screen 0 1600x1200x24 &

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.6'

      - name: Build with Maven
        run: mvn -B compile --file pom.xml
        env:
          DISPLAY: :1

      - name: Stop Xvfb
        run: killall Xvfb

  build-hmg:
   runs-on: ubuntu-latest
   needs: build-dev
   environment:
     name: hmg
   steps:
    - name: Start virtual display (Xvfb)
      run: Xvfb :1 -screen 0 1600x1200x24 &

    - name: Checkout repository (clone completo)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0           # clone completo (sem shallow)
        persist-credentials: false

    - name: Remove shallow flag (se existir)
      run: |
        if [ -f .git/shallow ]; then
          echo "Arquivo .git/shallow encontrado, removendo..."
          rm .git/shallow
        else
          echo "Nenhum arquivo .git/shallow encontrado"
        fi
        echo "Shallow? $(git rev-parse --is-shallow-repository)"

    - name: Configure git safe.directory e fetch completo
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --unshallow || echo "Repositório já não é shallow"
        git fetch --tags
        git fetch origin +refs/heads/*:refs/remotes/origin/*
        echo "Verificação final do clone:"
        echo "Shallow? $(git rev-parse --is-shallow-repository)"
        echo "Últimos commits:"
        git log -3 --oneline

    - name: Limpar cache Sonar (opcional para testes)
      run: rm -rf ~/.sonar/cache || echo "Cache sonar não existe ou não pôde ser removido"

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.18.0
      with:
        maven-version: '3.9.6'

    - name: Cache Sonar packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Final sanity check do repositório
      run: |
        echo "Verificando clone e arquivos importantes..."
        echo "Shallow? $(git rev-parse --is-shallow-repository)"
        test -f .git/shallow && echo ".git/shallow ainda existe" || echo "Clone completo confirmado"
        git status
        git remote -v

    - name: Build and analyze with SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        DISPLAY: :1
      run: |
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=GarraOne_EmprestimoFerramentaCI \
          -Dsonar.scm.enabled=true \
          -Dsonar.scm.provider=git \
          -Dsonar.verbose=true

    - name: Stop Xvfb
      run: killall Xvfb || echo "Xvfb já finalizado"

  build-prd:
    runs-on: ubuntu-latest
    needs: build-hmg
    environment:
      name: prd
    steps:
      - name: Start virtual display (Xvfb)
        run: Xvfb :1 -screen 0 1600x1200x24 &

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.6'

      - name: Package project with Maven
        env:
          DISPLAY: :1
        run: mvn -B package --file pom.xml

      - name: Create artifact folder
        run: mkdir staging

      - name: Copy artifacts
        run: cp target/*jar-with-dependencies.jar staging

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      - name: Stop Xvfb
        run: killall Xvfb
